// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise } from '../core/http.js';
import type { WidgetConfig } from '../types.js';

export class Config {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Get widget config
   * 
   * @example
   * ```ts
   * const widgetConfig = await client.config.retrieveWidget();
   * ```
   */
  retrieveWidget(options?: RequestOptions): APIPromise<WidgetConfig> {
    return this._client.requestAPI<WidgetConfig>(() => {
      return { method: 'GET', path: `/v1/config` };
    }, options);
  }
}
