// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions } from '../core/http.js';
import type { WidgetConfig } from '../types.js';

export class Config {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Get widget config
   */
  async retrieveWidget(options?: RequestOptions): Promise<WidgetConfig> {
    return this._client.request<WidgetConfig>({ method: 'GET', path: `/v1/config` }, options);
  }
}
