// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, RequestSpec, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import { Stream } from '../core/sse.js';
import type { ListConversationEventsResponse, ListConversationsResponse, WidgetConversation, WidgetEvent } from '../types.js';

export interface ConversationListParams {
  /**
   * Maximum number of results to return.
   */
  limit?: number;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string;
}

export interface ConversationCreateParams {
  /**
   * The visitor's opening message.
   */
  message: string;
}

export interface ConversationListEventsParams {
  /**
   * Maximum number of results to return.
   */
  limit?: number;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string;
}

export interface ConversationSubmitFeedbackParams {
  /**
   * A score between -1.0 and 1.0. -1.0 is the worst, 0.0 neutral, 1.0 the
   *  best — a thumbs-down/up UI maps to -1.0/1.0.
   */
  score: number;
  /**
   * Optional comment explaining the feedback.
   */
  comment?: string;
}

export interface ConversationApproveToolCallParams {
  /**
   * The tool call awaiting a decision, from the toolApprovalRequested event.
   */
  toolCallId: string;
}

export interface ConversationDenyToolCallParams {
  /**
   * The tool call awaiting a decision, from the toolApprovalRequested event.
   */
  toolCallId: string;
}

export interface ConversationSetToolCallContentParams {
  /**
   * The bare tool call to supply content for.
   */
  toolCallId: string;
  /**
   * The tool call's result content.
   */
  content: string;
}

export interface ConversationContinueParams {
  /**
   * The visitor's next message.
   */
  message: string;
}

export class Conversations {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List conversations
   * 
   * @example
   * ```ts
   * const page = await client.conversations.list();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(params?: ConversationListParams, options?: RequestOptions): Promise<Page<WidgetConversation>> {
    const _base = snapshotParams(params);
    const response = await this._client.request<ListConversationsResponse>({ method: 'GET', path: `/v1/conversations`, query: { limit: params?.limit, cursor: params?.cursor } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list({ ..._base, cursor: cursor }, options));
  }

  /**
   * Start a conversation
   * 
   * @example
   * ```ts
   * const widgetConversation = await client.conversations.create({ message: 'sample' });
   * ```
   */
  create(params: ConversationCreateParams, options?: RequestOptions): APIPromise<WidgetConversation> {
    return this._client.requestAPI<WidgetConversation>(() => {
      return { method: 'POST', path: `/v1/conversations`, body: { message: params.message } };
    }, options);
  }

  /**
   * Get a conversation
   * 
   * @example
   * ```ts
   * const widgetConversation = await client.conversations.retrieve('_123');
   * ```
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<WidgetConversation> {
    return this._client.requestAPI<WidgetConversation>(() => {
      return { method: 'GET', path: `/v1/conversations/${pathSegment('id', id)}` };
    }, options);
  }

  /**
   * List conversation events
   * 
   * @example
   * ```ts
   * const page = await client.conversations.listEvents('_123');
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async listEvents(id: string, params?: ConversationListEventsParams, options?: RequestOptions): Promise<Page<WidgetEvent>> {
    const _base = snapshotParams(params);
    const response = await this._client.request<ListConversationEventsResponse>({ method: 'GET', path: `/v1/conversations/${pathSegment('id', id)}/events`, query: { limit: params?.limit, cursor: params?.cursor } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.listEvents(id, { ..._base, cursor: cursor }, options));
  }

  /**
   * Stream conversation events
   * 
   * @example
   * ```ts
   * const stream = await client.conversations.streamEvents('_123');
   * for await (const event of stream) {
   *   // typed event payloads; housekeeping frames are skipped
   * }
   * ```
   */
  async streamEvents(id: string, options?: RequestOptions): Promise<Stream<WidgetEvent>> {
    const _spec: RequestSpec = { method: 'GET', path: `/v1/conversations/${pathSegment('id', id)}/events:stream`, stream: true };
    const response = await this._client.rawRequest(_spec, options);
    return new Stream<WidgetEvent>(response, options?.signal, options?.lastEventId, ['ping', 'open'], options?.reconnect === false ? undefined : (lastEventId) => this._client.rawRequest(_spec, { ...options, lastEventId }));
  }

  /**
   * Submit conversation feedback
   * 
   * @example
   * ```ts
   * await client.conversations.submitFeedback('_123', { score: 1.5 });
   * ```
   */
  submitFeedback(id: string, params: ConversationSubmitFeedbackParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      return { method: 'POST', path: `/v1/conversations/${pathSegment('id', id)}/feedback`, body: { score: params.score, comment: params.comment }, void: true };
    }, options);
  }

  /**
   * Approve a pending tool call
   * 
   * @example
   * ```ts
   * await client.conversations.approveToolCall('_123', { toolCallId: 'tool_call_123' });
   * ```
   */
  approveToolCall(id: string, params: ConversationApproveToolCallParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      return { method: 'POST', path: `/v1/conversations/${pathSegment('id', id)}/tool_calls/${pathSegment('toolCallId', params.toolCallId)}:approve`, void: true };
    }, options);
  }

  /**
   * Deny a pending tool call
   * 
   * @example
   * ```ts
   * await client.conversations.denyToolCall('_123', { toolCallId: 'tool_call_123' });
   * ```
   */
  denyToolCall(id: string, params: ConversationDenyToolCallParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      return { method: 'POST', path: `/v1/conversations/${pathSegment('id', id)}/tool_calls/${pathSegment('toolCallId', params.toolCallId)}:deny`, void: true };
    }, options);
  }

  /**
   * Supply a bare tool call's result
   * 
   * @example
   * ```ts
   * await client.conversations.setToolCallContent('_123', { toolCallId: 'tool_call_123', content: 'sample' });
   * ```
   */
  setToolCallContent(id: string, params: ConversationSetToolCallContentParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      return { method: 'POST', path: `/v1/conversations/${pathSegment('id', id)}/tool_calls/${pathSegment('toolCallId', params.toolCallId)}:setContent`, body: { content: params.content }, void: true };
    }, options);
  }

  /**
   * Send the next message
   * 
   * @example
   * ```ts
   * const widgetConversation = await client.conversations.continue('_123', { message: 'sample' });
   * ```
   */
  continue(id: string, params: ConversationContinueParams, options?: RequestOptions): APIPromise<WidgetConversation> {
    return this._client.requestAPI<WidgetConversation>(() => {
      return { method: 'POST', path: `/v1/conversations/${pathSegment('id', id)}:continue`, body: { message: params.message } };
    }, options);
  }
}
