// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment } from '../core/http.js';
import type { WidgetSessionCredentials } from '../types.js';

export interface SessionRenewWidgetParams {
  /**
   * Required workspace containing the authenticated session. Must match the
   *  session resolved from the bearer token; never authorizes access by itself.
   */
  workspaceId: string;
}

export class Session {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Renew a widget session token
   * 
   * @example
   * ```ts
   * const widgetSessionCredentials = await client.session.renewWidget({ workspaceId: 'workspace_123' });
   * ```
   */
  renewWidget(params: SessionRenewWidgetParams, options?: RequestOptions): APIPromise<WidgetSessionCredentials> {
    return this._client.requestAPI<WidgetSessionCredentials>(() => {
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', params.workspaceId)}/session:renew` };
    }, options);
  }
}
