// Generated by redwood. Do not edit by hand.

import { HttpClient } from './core/http.js';
import type { Logger, LogLevel } from './core/http.js';
import { Config } from './resources/config.js';
import { Conversations } from './resources/conversations.js';

export interface ClientOptions {
  /** API key. Defaults to the CADENYAWIDGETS_API_KEY environment variable. */
  apiKey?: string;
  /** Override the API base URL. Defaults to . */
  baseURL?: string;
  /** Max automatic retries for retryable failures. Defaults to 0. */
  maxRetries?: number;
  /**
   * Deadline for ordinary (non-streaming) requests in milliseconds; override
   * per request with `options.timeout`. Streams bound only response-header
   * acquisition — body lifetime stays under the caller's AbortSignal.
   * Defaults to 60000; a non-finite or <= 0 value disables the deadline.
   */
  timeout?: number;
  /** Headers sent with every request. */
  defaultHeaders?: Record<string, string>;
  /** Custom fetch implementation. */
  fetch?: typeof fetch;
  /** Destination for SDK logs. Defaults to `console`. */
  logger?: Logger;
  /** 'debug' | 'warn' (default) | 'off'. Never logs headers or bodies. */
  logLevel?: LogLevel;
}

export class CadenyaWidgets {
  readonly config: Config;
  readonly conversations: Conversations;

  private readonly _client: HttpClient;

  constructor(options: ClientOptions = {}) {
    // Presence is not validity: empty strings from options or environment
    // are configuration mistakes, not credentials.
    const apiKey = resolveOption('apiKey', options.apiKey, readEnv('CADENYAWIDGETS_API_KEY'));
    if (!apiKey) {
      throw new Error(
        "Missing API key. Pass it with `new CadenyaWidgets({ apiKey })` or set the CADENYAWIDGETS_API_KEY environment variable.",
      );
    }
    this._client = new HttpClient({
      baseURL: resolveOption('baseURL', options.baseURL, readEnv('CADENYAWIDGETS_BASE_URL')) ?? '',
      authHeader: () => ({ Authorization: `Bearer ${apiKey}` }),
      maxRetries: options.maxRetries ?? 0,
      timeout: options.timeout,
      defaultHeaders: { 'User-Agent': 'cadenyawidgets-typescript/1.0.1 (api 1.0)', ...options.defaultHeaders },
      fetch: options.fetch,
      logger: options.logger,
      logLevel: options.logLevel,
      defaults: {  },
    });
    this.config = new Config(this._client);
    this.conversations = new Conversations(this._client);
  }
}

function readEnv(name: string): string | undefined {
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } })
    .process?.env;
  return env?.[name];
}

// Presence is not validity: an explicitly provided option must be usable —
// a blank value is a configuration mistake and never silently falls back to
// the environment or a default. Only an OMITTED option reads the env.
function resolveOption(
  label: string,
  explicit: string | undefined,
  env: string | undefined,
): string | undefined {
  if (explicit !== undefined) {
    const value = explicit.trim();
    if (!value) {
      throw new Error(
        `${label} must not be blank when provided explicitly; omit it to use the environment instead.`,
      );
    }
    return value;
  }
  return env?.trim() || undefined;
}
